#pragma once
#include <hw.h>

#define WIFI_SSID "ANDROID AP"
#define WIFI_PASS "tes12345"
#define DEVICE_NAME "pio-master"
#define WIFI_HOSTNAME "pio-master"
#define FTP_USER "pio"
#define FTP_PASS "tes12345"

#define MASTER_BLACKLIST_DURATION_MS 5000
#define MASTER_WEATHER_STALE_MS 120000
#define MASTER_WEATHER_SYNC_RETRY_MS 30000

#define MASTER_UI_SCROLL_COOLDOWN_MS 120
#define MASTER_UI_FOCUS_MIN_INDEX 0
#define MASTER_UI_FOCUS_MAX_HOME 2
#define MASTER_UI_FOCUS_MAX_DEVICE_LIST 2
#define MASTER_UI_FOCUS_MAX_ESPNOW_CONTROL 2
#define MASTER_UI_FOCUS_MAX_SETTINGS 2