#pragma once

// Input pin configuration
#define INPUT_BUTTON_UP_PIN 6
#define INPUT_BUTTON_DOWN_PIN 0
#define INPUT_BUTTON_SELECT_PIN 4
#define INPUT_BUTTON_BACK_PIN 14

#define INPUT_JOYSTICK1_VRX_PIN 8
#define INPUT_JOYSTICK1_VRY_PIN 18
#define INPUT_JOYSTICK1_SW_PIN 17

#define INPUT_JOYSTICK2_VRX_PIN 16
#define INPUT_JOYSTICK2_VRY_PIN 15
#define INPUT_JOYSTICK2_SW_PIN 7

#define INPUT_BATTERY_ADC_PIN 1
#define INPUT_BATTERY_CHARGE_PIN -1